name: Run FPL Collector (manual)

on:
  workflow_dispatch:   # ✅ Manual trigger only

jobs:
  run-collector:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Ensure data folder exists
        run: mkdir -p data

      - name: Run data collector
        run: python collect_fpl_data.py

      - name: Commit data
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/
          if git diff --cached --quiet; then
            echo "No new data to commit"
          else
            git commit -m "FPL snapshot $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            git push
