name: Fetch FPL Data

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:     # Allows manual trigger from GitHub UI

jobs:
  fetch-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run FPL data collection script
        run: python collect_fpl_data.py

      - name: Debug: List files before commit
        run: |
          echo "Files in the 'data' directory before commit:"
          ls -alh data/

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit new snapshot
        run: |
          git add data/
          echo "Files staged for commit:"
          git status
          git diff --cached
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add FPL data snapshot - $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
            git push
