name: Run FPL Collector

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:  # Manual trigger

jobs:
  run-collector:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Ensure data folders exist
      run: |
        mkdir -p data
        mkdir -p docs/data

    - name: Run data collector
      run: python collect_fpl_data.py

    - name: Copy latest JSON to docs/data
      run: |
        cp data/*.json docs/data/

    - name: Commit data
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs/data/*
        if git diff --cached --quiet; then
          echo "No new data to commit"
        else
          git commit -m "Update dashboard data $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push https://github.com/${{ github.repository }}.git HEAD:main
        fi
